export { default } from './birdpaper-ui-icon';
export { default as IconCodeSLine } from './icon-code-s-line';
export { default as IconCodeSSlashLine } from './icon-code-s-slash-line';
export { default as IconCopyleftLine } from './icon-copyleft-line';
export { default as IconCopyrightLine } from './icon-copyright-line';
export { default as IconCss3Line } from './icon-css3-line';
export { default as IconDashboardLine } from './icon-dashboard-line';
export { default as IconDeleteBinLine } from './icon-delete-bin-line';
export { default as IconDiscLine } from './icon-disc-line';
export type {} from './icon-components';
